name: jvak
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  google_fonts: ^5.1.0
  toggle_switch: ^2.1.0
  provider: ^6.0.5
  webview_flutter: ^4.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.7
flutter:

  uses-material-design: true

  assets:
     - assets/

  fonts:
    - family: PassionOne
      fonts:
        - asset: assets/fonts/PassionOne-Regular.ttf
          weight: 400
        - asset: assets/fonts/PassionOne-Bold.ttf
          weight: 700
        - asset: assets/fonts/PassionOne-Black.ttf
          weight: 900
