name: jvak
description: 더욱 직관적인 UI, 더욱 다양해진 노래 일본 노래뿐만 아니라 한국 노래 역시 검색이 가능합니다

version: 3.0.1+27

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  google_fonts: ^6.1.0
  toggle_switch: ^2.1.0
  provider: ^6.1.1
  webview_flutter: ^4.2.4
  dio: ^5.3.3
  image_picker: ^1.0.4
  firebase_core: ^2.17.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4
  google_mobile_ads: ^5.0.0
  change_app_package_name: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  flutter_svg: ^2.0.7
flutter:

  uses-material-design: true

  assets:
     - assets/

  fonts:
    - family: PassionOne
      fonts:
        - asset: assets/fonts/PassionOne-Regular.ttf
          weight: 400
        - asset: assets/fonts/PassionOne-Bold.ttf
          weight: 700
        - asset: assets/fonts/PassionOne-Black.ttf
          weight: 900
