// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn7Grk6hbu3zcl_Na6BIDq40IuoUDw5Vs',
    appId: '1:969121728211:android:7f642dc05b1f88e923b626',
    messagingSenderId: '969121728211',
    projectId: 'jvak-cc511',
    databaseURL: 'https://jvak-cc511.firebaseio.com',
    storageBucket: 'jvak-cc511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC135nxUIcdI4vbyuFevU5bsqXfY7qMDmU',
    appId: '1:969121728211:ios:06cd3df2e571763023b626',
    messagingSenderId: '969121728211',
    projectId: 'jvak-cc511',
    databaseURL: 'https://jvak-cc511.firebaseio.com',
    storageBucket: 'jvak-cc511.appspot.com',
    androidClientId: '969121728211-j3tnj8i2qhiprn2co2tlqfnh3menf570.apps.googleusercontent.com',
    iosClientId: '969121728211-cljikd6msob4odbqnrp2rei3hun39ujc.apps.googleusercontent.com',
    iosBundleId: 'com.example.jvak',
  );
}
